# Generated by Django 5.1.3 on 2024-11-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="NewSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("reliability", models.FloatField()),
                ("source", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="RssData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("link", models.URLField()),
                ("published", models.TextField()),
                ("updated", models.TextField()),
                ("country", models.CharField(max_length=100)),
                ("image", models.JSONField()),
                ("summary", models.TextField()),
            ],
        ),
    ]
